name: Build Installer

on:
  push:
    branches: 
      - master
      - 'release-*'

env:
  BUILD_CONFIG: "Release"
  BUILDNUMBER: ${{github.run_number}}

jobs:
  build:
    name: Build the Ziti Desktop Edge for Windows Installer Package
    runs-on: windows-latest
    env:
      SOME_KEY: ${{ secrets.SOME_KEY }}
      ADV_INST_KEY: ${{ secrets.ADV_INST_KEY }}
      JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}
      gh_ci_key: ${{ secrets.GH_CI_KEY }}
      ZITI_DEBUG: "yes_please"
      
    steps:
      - uses: actions/checkout@master
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.5'
      - if: github.event_name == 'push'
        run: echo "GIT_BRANCH=$($env:GITHUB_REF.replace('refs/heads/', ''))" >> $env:GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "GIT_BRANCH=$env:GITHUB_HEAD_REF" >> $env:GITHUB_ENV
      - run: echo "$(go env GOPATH)\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Setup secrets
        run: |
          echo "${env:SOME_KEY}" > WinSign.b64
          echo "${env:ADV_INST_KEY}" > ADV_INST_KEY.key
          C:\Windows\System32\certutil.exe -decode WinSign.b64 Installer/WinSign.p12
      - name: Trying to run choco install.
        run: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: "Install Choco needs: advanced-installer wixtoolset zip ninja"
        run: choco install advanced-installer wixtoolset zip ninja --yes
      - name: Build the Service
        run: service/publish.bat
      - name: Upload service zip onto job
        uses: actions/upload-artifact@v2
        with:
          name: ziti-tunnel-win.zip
          path: "service/ziti-tunnel-win.zip"
        env:
          version: Get-Content .\version      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - run: ./ziti-edge-ui/npm install
      - run: npm i -g electron-packager
      - run: >
          electron-packager ./ziti-edge-ui Ziti-Desktop-Edge
            --overwrite --asar --electron-version=26.2.4 
            --platform=win32 --arch=x64 --prune=true 
            --out=./release-builds --icon=./ziti-edge-ui/app.ico
      - name: Restore nuget packages
        run: nuget restore ZitiDesktopEdge.sln
      - shell: pwsh
        name: Register Advanced Installer
        run: |
          $key=(Get-Content .\ADV_INST_KEY.key)
          .\Installer\reg.bat $key
      - name: Build UI and Assemble Installer
        run: powershell -File .\Installer\build.ps1
      - name: Upload installer onto job
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdgeClient
          path: "Installer/Output/Ziti Desktop Edge Client-*.exe"
        env:
          version: Get-Content .\version
  linux-build: 
    name: Build the Ziti Desktop Edge for Linux Deb & Rpm Installer Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - uses: pCYSl5EDgo/cat@1.0.1
        id: vars
        with:
          path: ./version
      - run: echo ${{ steps.vars.outputs.text }}
        env:
          APPVER: ${{ steps.vars.outputs.text }}
      - name: Show Version
        run: echo $APPVER
      - run: npm install
      - run: npm i -g electron-builder
      - run: electron-builder --linux deb rpm
      - name: Upload Linux Deb installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Deb-${{ steps.vars.outputs.text }}
          path: "dist/ziti-desktop-edge-${{ steps.vars.outputs.text }}.deb"
      - name: Upload Linux Rpm installer
        uses: actions/upload-artifact@v2
        with:
          name: ZitiDesktopEdge-Rpm-${{ steps.vars.outputs.text }}
          path: "dist/ziti-desktop-edge-${{ steps.vars.outputs.text }}.rpm"
        